baseurl: https://hp-wedding.netlify.app/
languageCode: en-us
title: Wedding
theme: autophugo
disableKinds:
  - taxonomy
  - term
Author:
  email: haingocvo96@gmail.com
  name: Hai Vo
params:
  thumb_quality: 100
  thumb_width: 2048
  description: WeddingPreview - Photo Gallery on Hugo
  footer:
    contact:
      buttonText: Send
      email:
        text: Email *
        warning: Please, enter your email.
      headline: Get in touch
      hide: no
      message:
        text: Message *
        warning: Please, enter your message
      name:
        text: Name *
        warning: Please, enter your name
      realEmail: example@example.org
      resetText: Reset
    copyright:
      name: Your name
    paragraph:
      headline: Magna feugiat sed adipiscing
      text: Welcome to our album!
        This webiste store picture about of life, love, journey and wedding.
    social:
      headline: Follow me
      links:
        - icon: fa-twitter
          label: Twitter
          url: '#'
        - icon: fa-facebook
          label: Facebook
          url: '#'
        - icon: fa-instagram
          label: Instagram
          url: '#'
        - icon: fa-github
          label: Github
          url: '#'
        - icon: fa-linkedin
          label: LinkedIn
          url: '#'
  header:
    links:
      - icon: fa-info-circle
        name: About
        url: '#footer'
  keywords: phugo, hugo, photogallery, photoblog, hugo theme

markup:
  goldmark:
    renderer:
      unsafe: true
